aws_region              = "ap-south-1"
aws_profile             = "soniboy"
vpc_cidr                = "10.1.0.0/16"
public_subnet           = ["10.1.1.0/24", "10.1.2.0/24"]
private_subnet          = ["10.1.3.0/24", "10.1.4.0/24"]
rds_subnet              = ["10.1.5.0/24", "10.1.6.0/24", "10.1.7.0/24"]
localip                 = ["120.138.124.154/32"]
bucket-name             = "terransible"
db_instance_name        = "db.t2.micro"
db_name                 = "soniboydb"
db_user                 = "soniboy"
db_password             = "soniboypass"
instance_type           = "t2.micro"
key_name                = "pkey"
public_key              = "/home/ubuntu/.ssh/id_rsa.pub"
elb_healthy_threshold   = "2"
elb_unhealthy_threshold = "2"
elb_timeout             = "3"
elb_interval            = "30"
